# Generated by Django 4.1.3 on 2022-11-20 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agencia', models.IntegerField()),
                ('conta', models.CharField(max_length=200)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('data_nasc', models.DateField()),
                ('hash_password', models.CharField(max_length=200)),
                ('salt_password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Transacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contaDestinatario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contaDestinatario', to='user.conta')),
                ('contaRemetente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contaRemetente', to='user.conta')),
            ],
        ),
        migrations.AddField(
            model_name='conta',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.CreateModel(
            name='Cartoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senha', models.IntegerField()),
                ('limite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.conta')),
            ],
        ),
    ]
